"""cria tabelas users e tasks

Revision ID: 376998c5801f
Revises: 
Create Date: 2026-03-17 06:50:49.145668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376998c5801f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_updates_author'))
        batch_op.drop_index(batch_op.f('idx_updates_ticket'))

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_tickets_agent'))
        batch_op.drop_index(batch_op.f('idx_tickets_customer'))
        batch_op.drop_index(batch_op.f('idx_tickets_priority'))
        batch_op.drop_index(batch_op.f('idx_tickets_status'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_tickets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_tickets_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('idx_tickets_customer'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_tickets_agent'), ['agent_id'], unique=False)

    with op.batch_alter_table('ticket_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_updates_ticket'), ['ticket_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_updates_author'), ['author_id'], unique=False)

    # ### end Alembic commands ###
